version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo Build started on `date`
      - yarn install
  build:
    commands:
      - yarn build:$ENVIRONMENT
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: dist
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'
